tox.ini: Remove ipdb
It makes tests take longer to install deps and now causes this error on
Python < 2.7, because of IPython 2.0.0 requiring 2.7:

    ERROR: IPython requires Python Version 2.7 or above.